### ISSUE TITLE
UnitsOfPresentation -- different issues (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#30] opened 2021-03-11 13:47 UTC
ch.fhir.ig.ch-emed#0.2.0 /ValueSet-UnitsOfPresentation.html

see discussions during eMed Projectathon, Pero Grgic knows the current state

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment] 2021-03-20 09:01
see issue #38  and CH-Pharm-Issue No. 19 https://art-decor.org/art-decor/decor-issues--ch-pharm-

**Comment by eHealth-Suisse** [comment] 2021-05-04 12:33
duplicate of now closed issue #38

**Closed by eHealth-Suisse** 2021-05-04 12:33 UTC
Labels: STU 0.2.0 Informative Ballot, duplicate
